server.port=8080

# Token simulado para IDaaS
auth.simulated.token=demo-token

# URLs de microservicios
services.historial.url=http://localhost:8081
services.citas.url=http://localhost:8082
services.inventario.url=http://localhost:8083
services.facturacion.url=http://localhost:8084
